### ISSUE TITLE
Installation: packages missing

### ISSUE THREAD

**Issue by funkchaser** [gramaziokohler/aixd_ara#42]
### Problem:
`kaleido` is missing:

On Windows 10, Rhino 7.0, ARA 0.9.3 installed using `conda` instructions.

### Warning:
`kaleido 0.2.1` causes issues on Windows (hangs up) as previously reported in https://gitlab.renkulab.io/ai-augmented-design/aixd/-/issues/70 .

A working solution is to `pip install kaleido==0.1.0.post1` as suggested in https://github.com/plotly/Kaleido/issues/134

### TODO:
add the correct version of kaleido to the requirements

**Comment by funkchaser** [comment]
For Mac #43, the above solution doesn't work. Instead use:
` $ pip install -U kaleido`

**Comment by gonzalocasas** [comment]
Closed with the removal of static plots
